# Generated by Django 4.0.3 on 2022-03-22 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmonicSignalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitude', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amplitude')),
                ('frequency', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frequency')),
                ('initial_phase', models.FloatField(verbose_name='Initial phase')),
                ('started_calc_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculating start time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('celery_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult', verbose_name='Celery result')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['-started_calc_at'],
            },
        ),
    ]
