version: "3.7"

services:
  redis:
    image: redis
    restart: always
    volumes:
      - redisvolume:/data
    env_file: ./.env

  worker:
    restart: always
    build:
      context: ./services/backend
    volumes:
      - ./services/backend:/app/backend/
    entrypoint: []
    command: ["./wait-for-it.sh", "db:5432", "--", "celery", "-A", "dsp", "worker"]
    env_file: ./.env
    depends_on:
      - redis
      - db

  flower:
    restart: always
    build:
      context: ./services/backend
    ports:
      - "5555:5555"
    entrypoint: []
    command: ["celery", "-A", "dsp", "flower"]
    env_file: ./.env
    depends_on:
      - redis
      - worker

  backend:
    restart: always
    build:
      context: ./services/backend
    ports:
      - "8000:8000"
    volumes:
      - ./services/backend:/app/backend/
    env_file: ./.env
    entrypoint: []
    command: ["./wait-for-it.sh", "db:5432", "--", "./dsp_run.sh"]
    depends_on:
      - db

  db:
    restart: always
    image: postgres
    ports:
      - '5432'
    volumes:
      - postgresqldbvolume:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgresqldbvolume:
    driver: local
  redisvolume:
    driver: local
