# Generated by Django 4.0.3 on 2022-03-29 17:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCorrelationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitudes_signal_1', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Amplitudes in signal 1')),
                ('frequencies_signal_1', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Frequencies in signal 1')),
                ('amount_of_points_signal_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount of points in signal 1')),
                ('amplitudes_signal_2', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Amplitudes in signal 2')),
                ('frequencies_signal_2', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Frequencies in signal 2')),
                ('amount_of_points_signal_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount of points in signal 2')),
                ('started_calc_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculating start time')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Task ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_correlation_results', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Simple correlation result',
                'verbose_name_plural': 'Simple correlation results',
                'ordering': ['-started_calc_at'],
            },
        ),
    ]
