# Generated by Django 4.0.3 on 2022-03-28 18:37

import re

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FourierTransformResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitudes', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Amplitudes')),
                ('frequencies', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Frequencies')),
                ('started_calc_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculating start time')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Task ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourier_transform_results', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Fourier transformation result',
                'verbose_name_plural': 'Fourier transformation results',
                'ordering': ['-started_calc_at'],
            },
        ),
    ]
