# Generated by Django 4.0.3 on 2022-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonic_signal_app', '0004_remove_harmonicsignalresult_celery_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonicsignalresult',
            name='task_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Task ID'),
        ),
    ]
